services:
  py-serialrpc:
    build: ./serialrpc
    image: py-serialrpc
    restart: always
    tty: true
    read_only: true
    user: "0"
    ports:
    - "5005:5005"
    extra_hosts:
    # - "m4-proxy:172.17.0.1"
    - "m4-proxy:host-gateway"
    command: m4-proxy 5000
